adj(ookii,big).
adj(chiisai,small).
adj(takai,expensive).
adj(yasui,cheap).
adj(atarashii,new).
adj(atarashii,fresh).
adj(furui,old).
adj(ii,good).
adj(warui,bad).
adj(muzukashii,difficult).
adj(yasashii,easy).
adj(yasashii,kind).
adj(tooi,far).
adj(chikai,near).
adj(oishii,good).
adj(oishii,tasty).
adj(mazui,bad-tasting).
adj(isogashii,busy).
adj(otsui,hot).
adj(samui,cold).
adj(tsumetai,cold).
adj(atatakai,warm).
adj(suzushii,cool).
adj(omoshiroi,interesting).
adj(omoshiroi,fun).
adj(tsumaratai,boring).
adj(semai,narrow).
adj(hiroi,wide).
adj(hiroi,spacious).
adj(takai,high).
adj(takai,tall).
adj(hikui,low).
adj(nagai,long).
adj(omoi,heavy).
adj(karoi,light).
adj(tsuyoi,strong).
adj(yowai,weak).
adj(kurai,dark).
adj(okarui,bright).
adj(okarui,cheerful).
adj(kawaii,cute).
adj(kawaii,pretty).
adj(omai,sweet).
adj(karai,hot).
adj(karai,spicy).
adj(atsui,thick).
adj(usui,thin).
adj(usui,weak).
adj(futoi,thick).
adj(hosoi,thin).
adj(wakai,young).
adj(sukunai,few).
adj(ooi,many).
adj(ooi,much).
adj(itai,painful).
adj(kitanai,dirty).
adj(kitanai,messy).
adj(abutai,dangerous).
adj(urusai,noisy).
adj(tanoshii,pleasant).
adj(hoshii,want).
adj(aoi,blue).
adj(akai,red).
adj(kiiroi,yellow).
adj(kuroi,black).
adj(shiroi,white).
adj(chairoi,brown).
adj(nurui,likewarm).
adj(nurui,tepid).
adj(marui,round).
adj(marui,circular).
adj(kirei,beatiful).
adj(kirei,clean).
adj(yuumei,famous).
adj(teinei,polite).
adj(suki,like).
adj(sarai,no-like).
adj(shizuka,quiet).
adj(hima,free).
adj(nigiyaka,lively).
adj(benri,convenient).
adj(benri,useful).
adj(genki,well).
adj(genki,healthy).
adj(iroiro,various).
adj(daijoubu,okay).
adj(joubu,healthy).
adj(joubu,strong).
adj(taihen,hard).
adj(raku,easy).
adj(raku,comfortable).
adj(iya,nasty).
adj(iya,disgusting).
adj(taisetsu,important).
adj(jouzu,skillful).
adj(heta,unskillful).
adj(isshoukenmei,hard).
adj(isshoukenmei,desperately).
adj(kiken,dangerous).
adj(kiken,risky).
adj(zannen,regrettable).
adj(zannen,unlucky).
adj(shinpoi,worry).
adj(shinpoi,concern).
adj(jiyuu,free).
adj(jiyuu,liberty).
adj(juubun,enough).
adj(dausuki,like-very-much).
adj(tekitou,suitable).
adj(tekitou,appropiate).
adj(tokubetsu,special).
adj(netsujin,enthusiastic).
adj(hitsuyou,necessary).
adj(hitsuyou,essential).
adj(majime,serious).
adj(majime,earnest).
adj(massugu,straight).
adj(muri,impossible).
adj(rippa,excellent).
adj(rippa,magneficient).

jap_adjs(L) :- findall(X, (adj(X,_)),L).
play_adjs() :- ask(),play_adjs().
ask() :- jap_adjs(Lj),random_member(X,Lj),write(X),nl,read(Y),adj(X,Y).
